### ISSUE TITLE
Ebean.mock() has protected access?

### ISSUE THREAD

**Issue by qwIvan** [ebean-orm/avaje-ebeanorm-mocker#1]

**Comment by rbygrave** [comment]
Yes it does. MockiEbean via avaje-ebeanorm-mocker has public access.

Question answered then?

**Comment by rbygrave** [comment]
So to add to that ... I have just added a runWithMock() to MockiEbean that takes a mock and either a Runnable or Callable so:

```java
      MockiEbean.runWithMock(mock, new Runnable() {
        @Override
        public void run() {
           // test code in here
        }
      });
```

So with Java8 lambda instead of the runnable that becomes nice.

Would that do what you want?
