### ISSUE TITLE
Mismatched API on InterceptDelete? - update to 6.15 API

### ISSUE THREAD

**Issue by spiltcoffee** [ebean-orm/avaje-ebeanorm-mocker#4]
The following commit in avaje-ebeanorm changed EbeanServer to return `boolean` instead of `void` for two `delete()` methods: https://github.com/ebean-orm/avaje-ebeanorm/commit/a578eda2b1561c93d1d150d314158077f062f187

Does the InterceptDelete interface in this project need to be updated to match the API change? It still has a `void delete()`, but no `boolean delete()`: https://github.com/ebean-orm/avaje-ebeanorm-mocker/blob/master/src/main/java/com/avaje/ebean/delegate/InterceptDelete.java

**Comment by rbygrave** [comment]
Yes almost certainly. I'll take a look.

Thanks.
