### ISSUE TITLE
Update to support ebean version 7.2.1 API

### ISSUE THREAD

**Issue by wenzhihong2003** [ebean-orm/avaje-ebeanorm-mocker#5]
in DelegateEbeanServer class is not implement method docStore method define in  EbeanServer interface. 

other quest: this project is step by step follow ebean with newest version?

**Comment by rbygrave** [comment]
*> class is not implement method docStore method*

Yes, I'll fix and release shortly.


*>  this project is step by step follow ebean with newest version?*

No, it just needs to support public API changes.

**Comment by wenzhihong2003** [comment]
:+1:
