### ISSUE TITLE
Does it work with Play 2.5 ?

### ISSUE THREAD

**Issue by hardfire** [ebean-orm/avaje-ebeanorm-mocker#6]
I am trying to do the following in the tests
```
    mockServer = mock(EbeanServer.class, withSettings().verboseLogging());
    when(mockServer.getName()).thenReturn("default");
    when(mockServer.toString()).thenReturn("Wazza");
    mockiEbean = MockiEbean.start(mockServer);
```
and when i try to do a Ebean.getDefaultServer().toString() , it returns `com.avaje.ebeaninternal.server.core.DefaultServer@405192e4` from the play controller, but within test it returns` "Wazza" `as desired . 

How can i get this running ?

**Comment by rbygrave** [comment]
If you step with a debugger what does that tell you?

**Comment by rbygrave** [comment]
I'll close this - reopen if you want to continue.
