### ISSUE TITLE
7.7.1 compatible - remove EbeanServer.runCacheWarming(bean, id)  and EbeanServer.runCacheWarming(beanclass) method

### ISSUE THREAD

**Issue by wenzhihong2003** [ebean-orm/avaje-ebeanorm-mocker#8]
the break-api is here: https://github.com/ebean-orm/avaje-ebeanorm/issues/647

**Comment by rbygrave** [comment]
Thanks.  It's good someone is keeping me in line :)  ...  I'll look to sort this today.
